services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=hall_of_fame;Username=postgres;Password=QWEasd123;Timeout=30;CommandTimeout=300
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: QWEasd123
      POSTGRES_DB: hall_of_fame
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d hall_of_fame" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: